---
name: Net-SDP
version: 0.04
author:
  - 'Nicholas Humfrey, njh@ecs.soton.ac.uk'
abstract: Session Description Protocol (rfc2327)
license: perl
requires:
  Net::hostent: 0
  Sys::Hostname: 0
  perl: 5.5.0
recommends:
  LWP::Simple: 0
build_requires:
  Module::Build: 0.18
provides:
  Net::SDP:
    file: lib/Net/SDP.pm
    version: 0.04
  Net::SDP::Media:
    file: lib/Net/SDP/Media.pm
    version: 0.04
  Net::SDP::Time:
    file: lib/Net/SDP/Time.pm
    version: 0.04
generated_by: Module::Build version 0.2611
