--- #YAML:1.0
name: Net-SDP
version: 0.05
author:
  - Nicholas J Humfrey, njh@cpan.org
abstract: Session Description Protocol (rfc2327)
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
